# Generated by Django 2.1.4 on 2019-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190104_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=models.TextField(max_length=300),
        ),
    ]
